version: '3'

services:
  go-rate-limit-test:
    build: .
    restart: always
    environment:
      - PORT=8080
      - LIMIT=60
      - WINDOW_TIME_SEC=60
    ports:
      - "8080:8080"
    labels:
      logging: enable
      service_name: go-rate-limit-test
    logging:
      options:
        max-size: "500M"
        max-file: "4"
        labels: "logging,service_name"